In [1]:
import numpy as np
import pandas as pd

In [2]:
from google.colab import drive
drive.mount('/content/drive')

Drive already mounted at /content/drive; to attempt to forcibly remount, call drive.mount("/content/drive", force_remount=True).

In [5]:
df = pd.read_csv('/content/drive/MyDrive/DataScience/cursos-prouni.csv - cursos-prouni.csv.csv')

df.head()

,grau,turno,mensalidade,bolsa_integral_cotas,bolsa_integral_ampla,bolsa_parcial_cotas,bolsa_parcial_ampla,curso_id,curso_busca,cidade_busca,uf_busca,cidade_filtro,universidade_nome,campus_nome,campus_external_id,nome,nota_integral_ampla,nota_integral_cotas,nota_parcial_ampla,nota_parcial_cotas
0,Bacharelado,Integral,9999.99,15.0,14.0,NaN,NaN,706710394154,Medicina,Campo Grande,MS,NTAwMjAwNDAyNzA0,Universidade Anhanguera - UNIDERP,CAMPO GRANDE - SEDE - Miguel Couto,706710,Medicina,740.22,726.46,NaN,NaN
1,Bacharelado,Noturno,9836.40,1.0,NaN,NaN,NaN,104191210567043,Enfermagem,Crateus,CE,MjMwNDAxODA0MTAz,Faculdade Princesa do Oeste - FPO,UNIDADE SEDE - São Vicente,1041912,Enfermagem,663.36,NaN,NaN,NaN
2,Bacharelado,Integral,9715.61,2.0,5.0,6.0,10.0,1002328574024,Medicina,Sao Paulo,SP,MzUxNTA2MTUwMzA4,Universidade Cidade de São Paulo - UNICID,UNIVERSIDADE CIDADE DE SÃO PAULO - UNICID - SE...,1002328,Medicina,739.62,738.08,738.96,718.64
3,Bacharelado,Noturno,9689.34,3.0,2.0,NaN,NaN,104191212798093,Psicologia,Crateus,CE,MjMwNDAxODA0MTAz,Faculdade Princesa do Oeste - FPO,UNIDADE SEDE - São Vicente,1041912,Psicologia,651.00,652.22,NaN,NaN
4,Bacharelado,Integral,9674.34,4.0,1.0,5.0,2.0,65899611932754,Medicina,Rio Branco,AC,MTIwMjAwNDAwNDAx,Faculdade Barão do Rio Branco - FAB,CAMPUS - RIO BRANCO - JARDIM EUROPA II - Jard...,658996,Medicina,758.32,723.94,734.92,711.26

In [22]:
df.describe(include="all")

,grau,turno,mensalidade,bolsa_integral_cotas,bolsa_integral_ampla,bolsa_parcial_cotas,bolsa_parcial_ampla,curso_id,curso_busca,cidade_busca,uf_busca,cidade_filtro,universidade_nome,campus_nome,campus_external_id,nome,nota_integral_ampla,nota_integral_cotas,nota_parcial_ampla,nota_parcial_cotas
count,41447,41447,41447.000000,32520.000000,25404.000000,8828.000000,13041.000000,4.144700e+04,41447,41447,41447,41447,41447,41447,4.144700e+04,41447,32520.000000,16802.000000,16350.000000,5519.000000
unique,3,5,NaN,NaN,NaN,NaN,NaN,NaN,296,1158,27,1172,1299,4774,NaN,296,NaN,NaN,NaN,NaN
top,Bacharelado,Curso a Distância,NaN,NaN,NaN,NaN,NaN,NaN,Administração,Sao Paulo,SP,MzUxNTA2MTUwMzA4,Centro Universitário Internacional - Uninter -...,UNIDADE SEDE - Centro,NaN,Administração,NaN,NaN,NaN,NaN
freq,19165,22926,NaN,NaN,NaN,NaN,NaN,NaN,2754,3224,11533,3224,7335,610,NaN,2754,NaN,NaN,NaN,NaN
mean,NaN,NaN,622.636966,1.535394,2.513541,1.873018,8.632544,4.207360e+13,NaN,NaN,NaN,NaN,NaN,NaN,6.786530e+05,NaN,575.982999,564.470439,527.517136,511.799638
std,NaN,NaN,606.442296,2.191578,3.019549,2.336403,18.372991,6.061552e+13,NaN,NaN,NaN,NaN,NaN,NaN,6.398410e+05,NaN,57.827594,57.869145,60.202170,56.787140
min,NaN,NaN,139.000000,0.000000,1.000000,1.000000,1.000000,2.248801e+07,NaN,NaN,NaN,NaN,NaN,NaN,2.240000e+02,NaN,450.000000,450.000000,450.000000,450.000000
25%,NaN,NaN,278.000000,0.000000,1.000000,1.000000,1.000000,6.460131e+11,NaN,NaN,NaN,NaN,NaN,NaN,1.172300e+04,NaN,544.360000,532.865000,453.980000,450.000000
50%,NaN,NaN,393.350000,1.000000,1.000000,1.000000,2.000000,2.003572e+12,NaN,NaN,NaN,NaN,NaN,NaN,6.587550e+05,NaN,580.740000,571.450000,532.420000,511.820000
75%,NaN,NaN,825.000000,2.000000,3.000000,2.000000,6.000000,1.036636e+14,NaN,NaN,NaN,NaN,NaN,NaN,1.058794e+06,NaN,614.145000,603.315000,573.235000,557.170000
max,NaN,NaN,9999.990000,58.000000,67.000000,74.000000,350.000000,2.008632e+14,NaN,NaN,NaN,NaN,NaN,NaN,2.008633e+06,NaN,781.200000,792.240000,776.360000,768.340000

In [24]:
print("O total de cursos foi de " + str(df.shape[0]))

O total de cursos foi de 41447

In [59]:
#removendo colunas de cidade e campus

list_drop_columns = ['cidade_filtro',
                     'campus_nome',
                     'campus_external_id']

df_aux = df.drop(columns=list_drop_columns)
df_aux.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 41447 entries, 0 to 41446
Data columns (total 17 columns):
 #   Column                Non-Null Count  Dtype
---  ------                --------------  -----
 0   grau                  41447 non-null  object
 1   turno                 41447 non-null  object
 2   mensalidade           41447 non-null  float64
 3   bolsa_integral_cotas  32520 non-null  float64
 4   bolsa_integral_ampla  25404 non-null  float64
 5   bolsa_parcial_cotas   8828 non-null   float64
 6   bolsa_parcial_ampla   13041 non-null  float64
 7   curso_id              41447 non-null  int64
 8   curso_busca           41447 non-null  object
 9   cidade_busca          41447 non-null  object
 10  uf_busca              41447 non-null  object
 11  universidade_nome     41447 non-null  object
 12  nome                  41447 non-null  object
 13  nota_integral_ampla   32520 non-null  float64
 14  nota_integral_cotas   16802 non-null  float64
 15  nota_parcial_ampla    16350 non-null  float64
 16  nota_parcial_cotas    5519 non-null   float64
dtypes: float64(9), int64(1), object(7)
memory usage: 5.4+ MB

In [60]:
df_aux.head()

,grau,turno,mensalidade,bolsa_integral_cotas,bolsa_integral_ampla,bolsa_parcial_cotas,bolsa_parcial_ampla,curso_id,curso_busca,cidade_busca,uf_busca,universidade_nome,nome,nota_integral_ampla,nota_integral_cotas,nota_parcial_ampla,nota_parcial_cotas
0,Bacharelado,Integral,9999.99,15.0,14.0,NaN,NaN,706710394154,Medicina,Campo Grande,MS,Universidade Anhanguera - UNIDERP,Medicina,740.22,726.46,NaN,NaN
1,Bacharelado,Noturno,9836.40,1.0,NaN,NaN,NaN,104191210567043,Enfermagem,Crateus,CE,Faculdade Princesa do Oeste - FPO,Enfermagem,663.36,NaN,NaN,NaN
2,Bacharelado,Integral,9715.61,2.0,5.0,6.0,10.0,1002328574024,Medicina,Sao Paulo,SP,Universidade Cidade de São Paulo - UNICID,Medicina,739.62,738.08,738.96,718.64
3,Bacharelado,Noturno,9689.34,3.0,2.0,NaN,NaN,104191212798093,Psicologia,Crateus,CE,Faculdade Princesa do Oeste - FPO,Psicologia,651.00,652.22,NaN,NaN
4,Bacharelado,Integral,9674.34,4.0,1.0,5.0,2.0,65899611932754,Medicina,Rio Branco,AC,Faculdade Barão do Rio Branco - FAB,Medicina,758.32,723.94,734.92,711.26

In [61]:
#identificando valores nulos suspeitos

df_aux.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 41447 entries, 0 to 41446
Data columns (total 17 columns):
 #   Column                Non-Null Count  Dtype
---  ------                --------------  -----
 0   grau                  41447 non-null  object
 1   turno                 41447 non-null  object
 2   mensalidade           41447 non-null  float64
 3   bolsa_integral_cotas  32520 non-null  float64
 4   bolsa_integral_ampla  25404 non-null  float64
 5   bolsa_parcial_cotas   8828 non-null   float64
 6   bolsa_parcial_ampla   13041 non-null  float64
 7   curso_id              41447 non-null  int64
 8   curso_busca           41447 non-null  object
 9   cidade_busca          41447 non-null  object
 10  uf_busca              41447 non-null  object
 11  universidade_nome     41447 non-null  object
 12  nome                  41447 non-null  object
 13  nota_integral_ampla   32520 non-null  float64
 14  nota_integral_cotas   16802 non-null  float64
 15  nota_parcial_ampla    16350 non-null  float64
 16  nota_parcial_cotas    5519 non-null   float64
dtypes: float64(9), int64(1), object(7)
memory usage: 5.4+ MB

In [62]:
df_aux[df_aux.isna().any(axis=1)]

,grau,turno,mensalidade,bolsa_integral_cotas,bolsa_integral_ampla,bolsa_parcial_cotas,bolsa_parcial_ampla,curso_id,curso_busca,cidade_busca,uf_busca,universidade_nome,nome,nota_integral_ampla,nota_integral_cotas,nota_parcial_ampla,nota_parcial_cotas
0,Bacharelado,Integral,9999.99,15.0,14.0,NaN,NaN,706710394154,Medicina,Campo Grande,MS,Universidade Anhanguera - UNIDERP,Medicina,740.22,726.46,NaN,NaN
1,Bacharelado,Noturno,9836.40,1.0,NaN,NaN,NaN,104191210567043,Enfermagem,Crateus,CE,Faculdade Princesa do Oeste - FPO,Enfermagem,663.36,NaN,NaN,NaN
3,Bacharelado,Noturno,9689.34,3.0,2.0,NaN,NaN,104191212798093,Psicologia,Crateus,CE,Faculdade Princesa do Oeste - FPO,Psicologia,651.00,652.22,NaN,NaN
5,Bacharelado,Integral,9650.00,8.0,15.0,NaN,NaN,65781564964,Medicina,Presidente Prudente,SP,Universidade do Oeste Paulista - UNOESTE,Medicina,738.92,728.86,NaN,NaN
6,Bacharelado,Integral,9564.00,3.0,5.0,NaN,NaN,65788486984,Medicina,Marilia,SP,Universidade de Marília - UNIMAR,Medicina,744.16,735.00,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
41441,Tecnológico,Curso a Distância,149.00,0.0,1.0,NaN,NaN,967113826055,Gestão Comercial,Taubate,SP,Universidade Paulista - UNIP,Gestão Comercial,504.18,NaN,NaN,NaN
41442,Licenciatura,Curso a Distância,149.00,1.0,NaN,NaN,NaN,994312865605,Sociologia,Paraiso do Tocantins,TO,Universidade Paulista - UNIP,Sociologia,502.36,NaN,NaN,NaN
41444,Tecnológico,Vespertino,139.00,1.0,NaN,NaN,NaN,1056445674232,Gestão de Recursos Humanos,Brasilia,DF,Centro Universitário Planalto do Distrito Fede...,Gestão de Recursos Humanos,580.76,NaN,NaN,NaN
41445,Bacharelado,Curso a Distância,139.00,1.0,NaN,NaN,NaN,96781210935,Serviço Social,Vitoria,ES,Universidade Paulista - UNIP,Serviço Social,548.26,NaN,NaN,NaN
41446,Tecnológico,Curso a Distância,139.00,3.0,1.0,NaN,NaN,200467412868575,Gestão Ambiental,Santarem,PA,Universidade Paulista - UNIP,Gestão Ambiental,605.32,573.70,NaN,NaN

In [82]:
#removendo linhas com notas NaN
df_aux.dropna(subset=['nota_integral_ampla', 'nota_integral_cotas', 'nota_parcial_ampla', 'nota_parcial_cotas'], inplace=True)
df_aux.info()

<class 'pandas.core.frame.DataFrame'>
Int64Index: 2203 entries, 2 to 41443
Data columns (total 17 columns):
 #   Column                Non-Null Count  Dtype
---  ------                --------------  -----
 0   grau                  2203 non-null   object
 1   turno                 2203 non-null   object
 2   mensalidade           2203 non-null   float64
 3   bolsa_integral_cotas  2203 non-null   float64
 4   bolsa_integral_ampla  2203 non-null   float64
 5   bolsa_parcial_cotas   2203 non-null   float64
 6   bolsa_parcial_ampla   2203 non-null   float64
 7   curso_id              2203 non-null   int64
 8   curso_busca           2203 non-null   object
 9   cidade_busca          2203 non-null   object
 10  uf_busca              2203 non-null   object
 11  universidade_nome     2203 non-null   object
 12  nome                  2203 non-null   object
 13  nota_integral_ampla   2203 non-null   float64
 14  nota_integral_cotas   2203 non-null   float64
 15  nota_parcial_ampla    2203 non-null   float64
 16  nota_parcial_cotas    2203 non-null   float64
dtypes: float64(9), int64(1), object(7)
memory usage: 309.8+ KB

In [83]:
df_aux.head()

,grau,turno,mensalidade,bolsa_integral_cotas,bolsa_integral_ampla,bolsa_parcial_cotas,bolsa_parcial_ampla,curso_id,curso_busca,cidade_busca,uf_busca,universidade_nome,nome,nota_integral_ampla,nota_integral_cotas,nota_parcial_ampla,nota_parcial_cotas
2,Bacharelado,Integral,9715.61,2.0,5.0,6.0,10.0,1002328574024,Medicina,Sao Paulo,SP,Universidade Cidade de São Paulo - UNICID,Medicina,739.62,738.08,738.96,718.64
4,Bacharelado,Integral,9674.34,4.0,1.0,5.0,2.0,65899611932754,Medicina,Rio Branco,AC,Faculdade Barão do Rio Branco - FAB,Medicina,758.32,723.94,734.92,711.26
10,Bacharelado,Integral,9023.07,4.0,4.0,5.0,5.0,65921511844324,Medicina,Itaperuna,RJ,Faculdade Redentor - FACREDENTOR,Medicina,741.06,729.02,730.98,722.82
13,Bacharelado,Integral,8508.54,2.0,1.0,7.0,2.0,104123711716094,Medicina,Belem,PA,Faculdade Metropolitana da Amazônia - FAMAZ,Medicina,741.36,739.90,760.80,715.10
20,Bacharelado,Integral,8281.38,3.0,1.0,6.0,2.0,105887911921884,Medicina,Imperatriz,MA,Universidade do Ceuma - Uniceuma - UNICEUMA,Medicina,756.46,737.88,747.14,717.60

In [84]:
#mensalidade mais barata registrada

print("Mensalidade mais barata registrada: " + str(df_aux['mensalidade'].min()))

Mensalidade mais barata registrada: 144.0

In [85]:
#mensalidade mais cara registrada

print("Mensalidade mais cara registrada: " + str(df_aux['mensalidade'].max()))

Mensalidade mais cara registrada: 9715.61

In [87]:
#menor nota integral (ampla)

print("Menor Nota Integral (Ampla): " + str(df_aux['nota_integral_ampla'].min()))

Menor Nota Integral (Ampla): 450.0

In [88]:
#maior nota integral (ampla)

print("Maior Nota Integral (Ampla): " + str(df_aux['nota_integral_ampla'].max()))

Maior Nota Integral (Ampla): 781.2

In [89]:
#menor nota integral (cotas)

print("Menor Nota Integral (Cotas): " + str(df_aux['nota_integral_cotas'].min()))

Menor Nota Integral (Cotas): 450.0

In [90]:
#maior nota integral (cotas)

print("Maior Nota Integral (Cotas): " + str(df_aux['nota_integral_cotas'].max()))

Maior Nota Integral (Cotas): 792.24

In [91]:
#menor nota parcial (ampla)

print("Menor Nota Parcial (Ampla): " + str(df_aux['nota_parcial_ampla'].min()))

Menor Nota Parcial (Ampla): 450.0

In [92]:
#maior nota parcial (ampla)

print("Maior Nota Parcial (Ampla): " + str(df_aux['nota_parcial_ampla'].max()))

Maior Nota Parcial (Ampla): 776.36

In [93]:
#menor nota parcial (cotas)

print("Menor Nota Parcial (Cotas): " + str(df_aux['nota_parcial_cotas'].min()))

Menor Nota Parcial (Cotas): 450.0

In [94]:
#maior nota parcial (cotas)

print("Maior Nota Parcial (Cotas): " + str(df_aux['nota_parcial_cotas'].max()))

Maior Nota Parcial (Cotas): 768.34

In [95]:
df_aux.to_csv('/content/drive/MyDrive/DataScience/cursos-prouni.csv - cursos-prouni-tratados.csv.csv', index=False)